---
- name: Install Mata Elang Platform
  hosts: all
  vars_files:
    - defaults/main.yml
  pre_tasks:
    - name: Set Timezone to local
      become: true
      timezone:
        name: "{{ timezone }}"
  tasks:
    - name: Install Docker Binary
      ansible.builtin.import_tasks:
        file: tasks/install-docker.yml

    - name: Install Kafka
      ansible.builtin.import_tasks:
        file: tasks/install-kafka.yml

    - name: Install Sensor
      ansible.builtin.import_tasks:
        file: tasks/install-sensor.yml

    - name: Install Hadoop
      ansible.builtin.import_tasks:
        file: tasks/install-hadoop.yml

    - name: Install Spark
      ansible.builtin.import_tasks:
        file: tasks/install-spark.yml

    - name: Install OpenSearch
      ansible.builtin.import_tasks:
        file: tasks/install-opensearch.yml