---
- name: Install Mata Elang Platform
  hosts: all
  vars_files:
    - defaults/main.yml
  pre_tasks:
    - name: Set Timezone to local
      become: true
      timezone:
        name: Asia/Jakarta
  tasks:
    - name: Run Kafka installation
      include_role:
        name: kafka_docker
      when: inventory_hostname in groups['kafka']

    - name: Run Snort Sensor Installation
      include_role:
        name: snort_sensor
      when: inventory_hostname in groups['sensor']

    - name: Run Hadoop Installation
      include_role:
        name: hadoop
      when: inventory_hostname in groups['hadoop']

    - name: Run Spark Installation
      include_role:
        name: spark_docker
      when: inventory_hostname in groups['spark']

    - name: Run Opensearch Installation
      include_role:
        name: opensearch_docker
      when: inventory_hostname in groups['opensearch']
