---
- name: Install Mata Elang Platform
  hosts: all
  vars_files:
    - defaults/main.yml
  pre_tasks:
    - name: Set Timezone to local
      timezone:
        name: Asia/Jakarta
    - name: Upgrade Ubuntu packages
      become: yes
      apt:
        update_cache: yes
        name: "*"
        state: latest
  tasks:
    - name: sensor installation
      include_role:
        name: snort_sensor
      when: inventory_hostname in groups['sensor']
    - name: kafka installation
      include_role:
        name: kafka_docker
      when: inventory_hostname in groups['kafka']
