---
#control-center
kafka_cluster_name: MataElangKafkaCluster
kafka_cluster_bootstrap_server: kafka:9092
kafka_cluster_zookeeper: zookeeper:2181

#kafka
kafka_config_zookeper: zookeeper:2181
config_plaintext_listener: yes
kafka_config_log_dirs: /tmp/kafka_mounts/logs
kafka_config_advertised_listeners: CLIENT://kafka:9092,EXTERNAL://172.17.0.1:9093
kafka_config_listeners: CLIENT://:9092,EXTERNAL://0.0.0.0:9093
kafka_config_security_proto: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
kafka_config_broker_listener: CLIENT

#mqtt-source
mqtt_host: 172.17.0.1
mqtt_port: 1883
mqtt_username: ""
mqtt_password: ""
mqtt_topic: mataelang/sensor/v3/+
kafka_bootstrap_servers: kafka:9092
kafka_topic: sensor_events

#zookeeper
anonymous_login: yes


