---
- name: Ensure Kafka directory exists
  ansible.builtin.file:
    path: "~/kafka"
    state: directory
    mode: 0755

- name: Ensure Kafka docker image dir exists
  ansible.builtin.file:
    path: "~/kafka/docker_image"
    state: directory
    mode: 0755

- name: Copy docker image kafka related files to machine
  ansible.builtin.copy:
    src: "files/docker_images/{{ item }}"
    dest: "~/kafka/docker_image/"
    mode: 0755
  with_items: "{{ kafka_image_filenames }}"

- name: Load Docker Images
  community.docker.docker_image_load:
    path: "~/kafka/docker_image/{{ item }}"
    timeout: 120
  with_items: "{{ kafka_image_filenames }}"

- name: Cleanup Docker image tar
  ansible.builtin.file:
    path: "~/kafka/docker_image/{{ item }}"
    state: absent
  with_items: "{{ kafka_image_filenames }}"

- name: Check if docker-compose.yaml file exists
  ansible.builtin.stat:
    path: ~/kafka/docker-compose.yml
  register: kafka_compose_file

- name: Stop the Services
  community.docker.docker_compose:
    project_src: ~/kafka
    remove_orphans: true
    remove_volumes: true
    state: absent
  when: kafka_compose_file.stat.exists

- name: Configure docker-compose environment
  ansible.builtin.template:
    src: ./kafka/docker-compose.yml.j2
    dest: "~/kafka/docker-compose.yml"
    mode: 0755

- name: Run the Services
  community.docker.docker_compose:
    project_src: ~/kafka
    state: present
