---
- name: Ensure OpenSearch directory exists
  file:
    path: "~/opensearch"
    state: directory
    mode: 0775

- name: Ensure Opensearch docker image dir exists
  file:
    path: "~/opensearch/docker_image"
    state: directory
    mode: 0775

- name: Increase number of memory map using sysctl
  become: true
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: Copy docker image Opensearch related files to machine
  ansible.builtin.copy:
    src: "files/docker_images/{{ item }}"
    dest: "~/opensearch/docker_image/"
    mode: 0775
  with_items: "{{ opensearch_image_filenames }}"

- name: Load Docker Images
  community.docker.docker_image_load:
    docker_host: "unix:/{{ ansible_env.XDG_RUNTIME_DIR }}/docker.sock"
    path: "~/opensearch/docker_image/{{ item }}"
  with_items: "{{ opensearch_image_filenames }}"

- name: Configure docker-compose environment
  ansible.builtin.template: 
    src: ./opensearch/docker-compose.yaml.j2
    dest: "~/opensearch/docker-compose.yaml"
    mode: 0775

- name: Configure Pipeline config file
  ansible.builtin.template:
    src: ./opensearch/pipeline.conf.j2
    dest: "~/opensearch/pipeline.conf"
    mode: 0775

- name: Running the Services
  community.docker.docker_compose:
    docker_host: "unix:/{{ ansible_env.XDG_RUNTIME_DIR }}/docker.sock"
    project_src: ~/opensearch
    state: present
  
