---
- name: Copy Docker Binary Archive to remote target
  ansible.builtin.copy:
    src: "files/{{ docker_archive_filename }}"
    dest: "/tmp/"
    mode: 0644

- name: Extract Docker Binary Archive
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/{{ docker_archive_filename }}"
    dest: "/usr/bin/"
    creates: "/usr/bin/dockerd"
    copy: false
    extra_opts: [--strip-components=1]

# How to run docker daemon ? This command will not persist
# - name: Running Docker Daemon
#   become: true
#   ansible.builtin.command:
#     cmd: dockerd

- name: Configure Docker systemd file
  become: true
  ansible.builtin.template:
    src: "./dockerd/docker.service.j2"
    dest: "/lib/systemd/system/docker.service"
    owner: root
    group: root
    mode: 0755

- name: Ensure Docker directory exists
  become: true
  ansible.builtin.file:
    path: "/usr/local/lib/docker/cli-plugins"
    mode: 0700
    state: directory

- name: Install Docker Compose plugin
  become: true
  ansible.builtin.copy:
    src: "files/{{ docker_compose_plugin_archive_filename }}"
    dest: "/usr/local/lib/docker/cli-plugins/docker-compose"
    mode: 0755

- name: Restart service cron also issue daemon-reload to pick up config changes
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: docker
