---
- name: Ensure OpenSearch directory exists
  ansible.builtin.file:
    path: "~/opensearch"
    state: directory
    mode: 0755

- name: Ensure Opensearch docker image dir exists
  ansible.builtin.file:
    path: "~/opensearch/docker_image"
    state: directory
    mode: 0755

- name: Increase number of memory map using sysctl
  become: true
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: Copy docker image Opensearch related files to machine
  ansible.builtin.copy:
    src: "files/docker_images/{{ item }}"
    dest: "~/opensearch/docker_image/"
    mode: 0755
  with_items: "{{ opensearch_image_filenames }}"

- name: Load Docker Images
  community.docker.docker_image_load:
    path: "~/opensearch/docker_image/{{ item }}"
    timeout: 120
  with_items: "{{ opensearch_image_filenames }}"

- name: Cleanup Docker image tar
  ansible.builtin.file:
    path: "~/opensearch/docker_image/{{ item }}"
    state: absent
  with_items: "{{ opensearch_image_filenames }}"

- name: Check if docker-compose.yaml file exists
  ansible.builtin.stat:
    path: ~/opensearch/docker-compose.yml
  register: opensearch_compose_file

- name: Stop the Services
  community.docker.docker_compose:
    project_src: ~/opensearch
    remove_orphans: true
    remove_volumes: true
    state: absent
  when: opensearch_compose_file.stat.exists

- name: Configure docker-compose environment
  ansible.builtin.template:
    src: ./opensearch/docker-compose.yaml.j2
    dest: "~/opensearch/docker-compose.yaml"
    mode: 0755

- name: Configure Pipeline config file
  ansible.builtin.template:
    src: ./opensearch/pipeline.conf.j2
    dest: "~/opensearch/pipeline.conf"
    mode: 0755

- name: Run the Services
  community.docker.docker_compose:
    project_src: ~/opensearch
    state: present
