# code: language=yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ubuntu20.04
    box: ubuntu/focal64
    memory: 1024
    cpu: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
provisioner:
  name: ansible
verifier:
  name: ansible
