---
- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: present
    update_cache: true

- name: Remove old version of Docker
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    autoremove: true

- name: Install required packages to setup repository
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Register Docker Official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker-ubuntu.asc
    mode: 0644
    force: true

- name: Add Docker Official repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable"
    filename: docker-ubuntu
    state: present
    update_cache: true

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Add the user current user to 'docker' group
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    group: docker
